### ISSUE TITLE
Versioned Check CLI

### ISSUE THREAD

**Issue by ghost** [DataTig/DataTig#19]
https://github.com/DataTig/DataTig/commit/ec256c4a403b73d886d6dbebd9526d386dec1019

**Comment by odscjames** [comment]
Here's a github actions file that will work with this:

(you'd want a if branch name != main too)

```
name: Check
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Setup python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11
        architecture: x64
    - run: pip install git+https://github.com/datatig/datatig@b3643d509424bb77ee0a9ec0b53518bd25adf393
    - name: Setup default branch locally without switching current branch
      run: git fetch origin main:main
    - run: python -m datatig versionedcheck . main $GITHUB_SHA --mode=all_in_changed_records

```
